apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prodspek_arealplan
  tags:
    - public
spec:
  type: documentation
  lifecycle: production
  owner: felles_kartdatabase
  system: standardisering
